name: Testing the Python code

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.10" ]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with pycodestyle
        run: |
          pycodestyle shop/tests shop/*.py
      - name: Set testing environment
        run: |
          echo "from .settings import *" > shop/settings_test.py
          echo "DATABASES['default']['ENGINE'] = 'django.db.backends.postgresql'" >> shop/settings_test.py
          echo "DATABASES['default']['NAME'] = ':memory:'" >> shop/settings_test.py
          echo "TEST_DATABASE_PREFIX = 'test_'" >> shop/settings_test.py
      - name: Test with pytest
        run: |
          python manage.py test
